import 'package:flutter/material.dart';

import 'form_wizard_field_model.dart';

/// Builds the fields for a single dynamic array item.
typedef FormWizardArrayFieldBuilder =
    List<FormWizardFieldModel> Function(FormWizardArrayItemContext context);

/// Builds custom add/remove/reorder controls for dynamic field arrays.
typedef FormWizardArrayControlBuilder =
    Widget Function(BuildContext context, VoidCallback action);

/// Context passed to [FormWizardFieldArrayModel.fieldBuilder].
class FormWizardArrayItemContext {
  /// Creates context for one dynamic array item.
  const FormWizardArrayItemContext({
    required this.arrayName,
    required this.itemId,
    required this.index,
  });

  /// The parent array name.
  final String arrayName;

  /// Stable item ID generated by the form.
  final String itemId;

  /// Current visual index.
  final int index;

  /// Creates a stable field name for this array item.
  ///
  /// For example, `context.fieldName('phone')` may produce
  /// `phones.fw_1.phone`.
  String fieldName(String name) => '$arrayName.$itemId.$name';
}

/// Defines a repeatable group of fields.
class FormWizardFieldArrayModel {
  /// Creates a dynamic field array definition.
  const FormWizardFieldArrayModel({
    required this.name,
    required this.fieldBuilder,
    this.label,
    this.initialItemCount = 1,
    this.minItems = 0,
    this.maxItems,
    this.itemSpacing = 12,
    this.addButtonBuilder,
    this.removeButtonBuilder,
    this.moveUpButtonBuilder,
    this.moveDownButtonBuilder,
  }) : assert(initialItemCount >= 0),
       assert(minItems >= 0);

  /// Unique name for this field array.
  final String name;

  /// Optional label rendered above the array.
  final String? label;

  /// Builds fields for each item.
  final FormWizardArrayFieldBuilder fieldBuilder;

  /// Number of items created when the form first mounts.
  final int initialItemCount;

  /// Minimum number of items allowed.
  final int minItems;

  /// Maximum number of items allowed.
  final int? maxItems;

  /// Vertical spacing between array items.
  final double itemSpacing;

  /// Optional custom add button builder.
  final FormWizardArrayControlBuilder? addButtonBuilder;

  /// Optional custom remove button builder.
  final FormWizardArrayControlBuilder? removeButtonBuilder;

  /// Optional custom move-up button builder.
  final FormWizardArrayControlBuilder? moveUpButtonBuilder;

  /// Optional custom move-down button builder.
  final FormWizardArrayControlBuilder? moveDownButtonBuilder;
}
